### ISSUE TITLE
Not Secure Warning on 1.21

### ISSUE THREAD

**Issue by zikehalil3535** [4drian3d/SignedVelocity#112]
Hello, Im using Signed Velocity and still taking same warning on 1.21
![Screenshot_1](https://github.com/user-attachments/assets/43aa47a4-1b78-4352-9564-9c9353f10d70)

**Comment by ajh123** [comment]
You need to install [VPacketEvents](https://modrinth.com/plugin/vpacketevents) on your proxy.

**Comment by zikehalil3535** [comment]
> You need to install [VPacketEvents](https://modrinth.com/plugin/vpacketevents) on your proxy.

Already have.

**Comment by 4drian3d** [comment]
Just in case, are you using ViaVersion?

**Comment by ajh123** [comment]
> Just in case, are you using ViaVersion?

On my proxy I have these plugins installed:

```yaml
        plugins:
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/MapModCompanion.jar
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/SignedVelocity-Proxy-1.2.4.jar
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/ViaRewind-4.0.3-SNAPSHOT.jar
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/ViaVersion-5.0.4-SNAPSHOT.jar
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/ViaBackwards-5.0.4-SNAPSHOT.jar
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/VPacketEvents-1.1.0.jar
          - url: http://10.0.0.12:82/server_setup/proxy/plugins/voicechat-velocity-2.5.24.jar
```

Not sure what @zikehalil3535 has, but for me I don't get that warning.
